// <auto-generated />
using AuthenticationLab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthenticationLab.Migrations
{
    [DbContext(typeof(CrashDbContext))]
    [Migration("20220406152307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthenticationLab.Models.Crash", b =>
                {
                    b.Property<long>("CRASH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BICYCLIST_INVOLVED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CITY")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COMMERCIAL_MOTOR_VEH_INVOLVED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("COUNTY_NAME")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CRASH_DATETIME")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CRASH_SEVERITY_ID")
                        .HasColumnType("int");

                    b.Property<string>("DISTRACTED_DRIVING")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DOMESTIC_ANIMAL_RELATED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DROWSY_DRIVING")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DUI")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IMPROPER_RESTRAINT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("INTERSECTION_RELATED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("LAT_UTM_Y")
                        .HasColumnType("double");

                    b.Property<double>("LONG_UTM_X")
                        .HasColumnType("double");

                    b.Property<string>("MAIN_ROAD_NAME")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("MILEPOINT")
                        .HasColumnType("double");

                    b.Property<string>("MOTORCYCLE_INVOLVED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NIGHT_DARK_CONDITION")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OLDER_DRIVER_INVOLVED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OVERTURN_ROLLOVER")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PEDESTRIAN_INVOLVED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ROADWAY_DEPARTURE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ROUTE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SINGLE_VEHICLE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TEENAGE_DRIVER_INVOLVED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UNRESTRAINED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WILD_ANIMAL_RELATED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WORK_ZONE_RELATED")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CRASH_ID");

                    b.ToTable("mytable");
                });
#pragma warning restore 612, 618
        }
    }
}
